contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #shotgun_cbgp channel"
    url: https://nfcore.slack.com/channels/shotgun_cbgp
    about: Discussion about the nf-core/shotgun_cbgp pipeline
